.TH HSH 1 "March 2024" "Version 1.0" "Simple Shell Manual"

.SH NAME
hsh \- A simple UNIX command-line shell

.SH SYNOPSIS
.B hsh
[\fIOPTIONS\fR]

.SH DESCRIPTION
.B hsh
is a lightweight shell that executes user commands and built-in functions.

.SH BUILT-IN COMMANDS
The following built-in commands are supported:

.TP
.B cd
Change the current working directory.

.TP
.B env
Print the current environment variables.

.TP
.B exit
Exit the shell.

.SH USAGE
Commands can be run interactively or from a script.

.SH EXAMPLES
.EX
$ hsh
#cisfun$ ls
.EX

.SH SEE ALSO
bash(1), sh(1)
