
.TH HSH_CD 1 "March 2024" "Version 1.0" "Simple Shell Manual"

.SH NAME
cd \- Change the current working directory

.SH SYNOPSIS
.B cd
[\fIDIRECTORY\fR]

.SH DESCRIPTION
The 
.B cd
command changes the current directory.

.SH EXAMPLES
Change to `/home/user`:
.EX
#cisfun$ cd /home/user
.EX

Move to the previous directory:
.EX
#cisfun$ cd -
.EX

.SH SEE ALSO
hsh(1), pwd(1)
