.TH HSH_ENV 1 "March 2024" "Version 1.0" "Simple Shell Manual"

.SH NAME
env \- Print environment variables

.SH SYNOPSIS
.B env

.SH DESCRIPTION
The 
.B env
command prints all environment variables.

.SH EXAMPLES
List all environment variables:
.EX
#cisfun$ env
.EX

.SH SEE ALSO
printenv(1), export(1)
