.TH HSH_EXIT 1 "March 2024" "Version 1.0" "Simple Shell Manual"

.SH NAME
exit \- Exit the shell

.SH SYNOPSIS
.B exit
[\fIstatus\fR]

.SH DESCRIPTION
The 
.B exit
command terminates the shell.

.SH EXAMPLES
Exit with status `0`:
.EX
#cisfun$ exit 0
.EX

Exit with status `1`:
.EX
#cisfun$ exit 1
.EX

.SH SEE ALSO
hsh(1)
